sudo: required
dist: bionic

language: cpp

compiler:
- gcc

before_install:
- sudo apt update

install:
- sudo apt install libglew-dev libglfw3-dev libsdl2-dev

script:
  # Build and run tests
- cd tests
- mkdir build
- cd build
- cmake ..
- make
- git clone https://github.com/jmckiern/nes-tests.git
- export AUDIODEV=null
- ./NES-Emulator-Test
- cd ../../

  # Build main project
- mkdir build
- cd build
- cmake ..
- make
- cd ..

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: EaUHiirTGa+MUTGC0ggPZUEKWrQnxWFGbIltBLSrrffkvFGxv2j6mb5sRwbaMojH3YGURrbjUwLnl8cbgGdV/0rHi1rK8H13JdhnjSUZBI7PTjBpzyZwlAVwsbw+JMbQ9J9Hr+mV2ad8MH7GG48mMYQwhuow6cMGzBX+BtKAAPwDqFngpsTpz2vkZH6PKwc1579Zc59ORWHn9c4QQro4Z56JiRP14bEYVNh0JYDIWnQWzUCuMrFmKdzL8EnCDuHX+uRIH07Q3/dLvPjtisjeGbXPnLrWvIJrHM9IZZGHTqVCEPBIAEN3ERecxqFPR6UracmwqFd2CQxrVkpfwLgU04y9LbdiH0dyDVFz2g1Dwbfeeg0Pr9Wy136UNaX3E7ZNuLDFevdij0RwqH7J8NvxpQbemPxa5/uIPYDvSNqW2BpesP+ktFeWdivwW6yzQQGu6nXfrjXmUegplNM5y0zjLgyyLQcLDmaMZWYAaVt35DN92XL7X5MKcGeHJDwAnYEkEnMZEyPUioCIl73znCJ0ffBUhu/QXNEigZf5apfxGBcWOCX2f2W0yw8UwlP11yoITMZciKPpdurq2rlmGEMrEYBT6Ash6+tR7FJzdOLzF16tRGpnvxu1DOGZklEQBoXrnRhS85lbFAMx7cr2FbD5212tY17cQzJ6rsTSafyqw4w=
  file: NES-Emulator
  on:
    repo: JMcKiern/NES-Emulator
    branch: master
    tags: true
