sudo: required
dist: bionic
language: cpp

compiler:
    - gcc

install:
    - sudo apt install libglew-dev libglfw3-dev libsdl2-dev

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
