sudo: required
dist: cosmic
language: cpp

compiler:
    - gcc

before_install:
    - sudo apt update

install:
    - sudo apt install libglew-dev libglfw3-dev libsdl2-dev

script:
    - mkdir build
    - cd build
    - cmake ..
    - make

deploy:
    provider: releases
    api_key: "GITHUB OAUTH TOKEN"
    file: NES-Emulator
    skip_cleanup: true
    draft: true
    on:
        branch: travis
