environment:
  CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
  VCPKG_TRIPLET: "x64-windows"

cache:
  - "C:/Tools/vcpkg/installed/"

configuration:
  - Release

image: Visual Studio 2017

install:
  - ps: vcpkg install glfw3:$env:VCPKG_TRIPLET
  - ps: vcpkg install glew:$env:VCPKG_TRIPLET
  - ps: vcpkg install portaudio:$env:VCPKG_TRIPLET
  - ps: vcpkg list

build_script:
  # Build and run tests
  - ps: mkdir build
  - ps: cd build
  - ps: cmake -G"$env:CMAKE_GENERATOR" -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DNES_DISABLE_IO=ON ..
  - ps: cmake --build . --target ALL_BUILD --config $env:CONFIGURATION
  - ps: git clone -q https://github.com/jmckiern/nes-tests.git
  - ps: iex ./$env:CONFIGURATION/NES-Emulator.exe --test ../tests/testlist.csv
  - ps: cd ..
  - ps: rm -rf build

  # Build main project
  - ps: mkdir build
  - ps: cd build
  - ps: cmake -G"$env:CMAKE_GENERATOR" -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - ps: cmake --build . --target ALL_BUILD --config $env:CONFIGURATION
  - ps: cd ..

after_build:
  - ps: 7z a -tzip NES-Emulator_$env:VCPKG_TRIPLET.zip ./build/$env:CONFIGURATION/*

artifacts:
  - path: "build/NES-Emulator_$(VCPKG_TRIPLET).zip"
    name: NES-Emulator

deploy:
  provider: GitHub
  description: ""
  auth_token:
    secure: m3cBOTDVPvla+9ySt/Q2Bt6dYjkOrNPPGc/mH1txvGRRbGK07uLLLlkKDGU/u+BI
  on:
    APPVEYOR_REPO_TAG: true
  artifact: NES-Emulator
